// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdKQkPYHHPXj40OS2fLAyOvS5mtqbEn5g',
    appId: '1:842505998331:web:49dd080b1e35e98b53855e',
    messagingSenderId: '842505998331',
    projectId: 'job-tracker-bb997',
    authDomain: 'job-tracker-bb997.firebaseapp.com',
    storageBucket: 'job-tracker-bb997.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkpCRYkz3tl7J2UZqehI8CsEoUVc-5yLI',
    appId: '1:842505998331:android:bf1f204516a9a5dd53855e',
    messagingSenderId: '842505998331',
    projectId: 'job-tracker-bb997',
    storageBucket: 'job-tracker-bb997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPcctAfRiAPBF2D2QaQ-9CLRiXII2BHLg',
    appId: '1:842505998331:ios:35276dd37dc63e2d53855e',
    messagingSenderId: '842505998331',
    projectId: 'job-tracker-bb997',
    storageBucket: 'job-tracker-bb997.appspot.com',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPcctAfRiAPBF2D2QaQ-9CLRiXII2BHLg',
    appId: '1:842505998331:ios:ca32579fe79828c153855e',
    messagingSenderId: '842505998331',
    projectId: 'job-tracker-bb997',
    storageBucket: 'job-tracker-bb997.appspot.com',
    iosBundleId: 'com.example.notebook.RunnerTests',
  );
}
